### ISSUE TITLE
README.md requested improvement

### ISSUE THREAD

**Issue by brown** [bazelbuild/java_tools#22]
Please modify the README.md so that it shows the exact command needed to check out the Java tools commit.  For older releases I was able to just execute "git checkout SHA" because the commit was accessible from master or some other public branch.  Recently, I've needed to do "git fetch http://github.com/bazelbuild/bazel.git SHA && git checkout SHA".  It would have been helpful if that sequence were in the README.md file, so I could just paste it into my shell.
Thanks!

**Comment by comius** [comment]
Do you mean adding

```shell
git fetch http://github.com/bazelbuild/bazel.git SHA && git checkout SHA
```

to the README.md?

I'm a bit skeptical about fetch and checkout. Should there also be a clone?

It this helps you, I can add it. 

Otherwise you should still set the SHA, right?

**Comment by comius** [comment]
Closing, because there was no response.
