### ISSUE TITLE
Wrong url listed in 8.0 release notes

### ISSUE THREAD

**Issue by DieBauer** [bazelbuild/java_tools#24]
The release notes state that, in order to override versions you can specify a github url:
`        "https://github.com/bazelbuild/java_tools/releases/download/javac11-8.0/java_tools_javac11_linux-v8.0.zip",` 

This does not resolve, and should be changed to `https://github.com/bazelbuild/java_tools/releases/download/javac11_8.0/java_tools_javac11_linux-v8.0.zip`

It looks like the previous releases were released with `javac11-<version>`, but 8.0. with `_`.

**Comment by comius** [comment]
Fixed.
