### ISSUE TITLE
release: java_tools_javac11-v9.0 release

### ISSUE THREAD

**Issue by davido** [bazelbuild/java_tools#25]
New release should be conducted, once the Error Prone PR is merged: [1].

[1] https://github.com/bazelbuild/bazel/pull/11426

**Comment by davido** [comment]
Thanks for working on it.

Once new release candidate is created by `src/create_java_tools_release.sh`, I can upload fist PR with new release candidates `java_tools` artifacts.

**Comment by philwo** [comment]
Hey, thanks for offering to do that. The number of places where we have to edit the URLs and hashes is crazy. 😅

I already prepared the PR before reading your message here: https://github.com/bazelbuild/bazel/pull/11665

**Comment by philwo** [comment]
Commands ran for this release:

```
$ src/create_java_tools_release.sh --commit_hash 239b2aab17cc1f007b2221ada9074bbe0c58db88 --java_tools_version 9.0 --java_version 11 --rc 1 --release false
$ src/create_java_tools_release.sh --java_tools_version 9.0 --java_version 11 --rc 1 --release true
```

PR for testing / merging: https://github.com/bazelbuild/bazel/pull/11665

**Comment by philwo** [comment]
Release pushed: https://github.com/bazelbuild/java_tools/releases/tag/javac11_v9.0

**Comment by philwo** [comment]
Bazel switched to new java_tools version: https://github.com/bazelbuild/bazel/commit/5585a182659fb45720283dae3a36a05a09c2e54e

I think we're done here. :)

**Comment by davido** [comment]
> I think we're done here. :)

Thanks so much for your help!
