### ISSUE TITLE
Release Documentation missing toolchain flags

### ISSUE THREAD

**Issue by ulfjack** [bazelbuild/java_tools#26]
The release documentation should mention the toolchain flags. Right now it sounds like the only necessary step is to add the WORKSPACE stanzas, which is clearly not correct.

**Comment by comius** [comment]
The java_tools for some time now provide only the sources/binaries. Toolchain definitions are a part of Bazel and are documented there now. With Java platformization the flags became more general - that is just referring to Java version not actual location of the definition.
