### ISSUE TITLE
release: java_tools_javac14-v1.0 release

### ISSUE THREAD

**Issue by davido** [bazelbuild/java_tools#28]
Now, that this [PR](https://github.com/bazelbuild/bazel/pull/11514) is merged, new `java_tools_javac14` release should be conducted.

Cc @philwo.

**Comment by philwo** [comment]
I'll have a look at this today.

**Comment by philwo** [comment]
Buildkite pipeline finished successfully: https://buildkite.com/bazel-trusted/java-tools-binaries-java/builds/135

I'm about to run these commands now:

```
$ src/create_java_tools_release.sh --commit_hash fe291f7dcadc20eb85cff07b2cd4d899d79fba71 --java_tools_version 1.0 --java_version 14 --rc 1 --release false
$ src/create_java_tools_release.sh --java_tools_version 1.0 --java_version 14 --rc 1 --release true
```

**Comment by philwo** [comment]
Done:

```
releases/javac14/v1.0/java_tools_javac14_linux-v1.0.zip 196128eadc68a55fb42a1f990c84ee816f5b29320a72fe542fcfc4206ac3978a
releases/javac14/v1.0/java_tools_javac14_windows-v1.0.zip a6c69fd89b87fccc4c75203be6b407a1ca22cbdb54cffbd445f874281a933149
releases/javac14/v1.0/java_tools_javac14_darwin-v1.0.zip e20f002ceb3f3353d64c022e1f3400d8539ee56ffcfd4a6680d73d6a2cac938b
```

@davido Can you take it from here?

**Comment by philwo** [comment]
Release uploaded to GitHub, too: https://github.com/bazelbuild/java_tools/releases/tag/javac14_v1.0

**Comment by davido** [comment]
Thanks, @philwo!

**Comment by davido** [comment]
@philwo 

Thanks again, it works like a charm see updated java 14 toolchain example repository: [1], and updated gerrit change: [2].

[1] https://github.com/davido/bazel_java_toolchain14/blob/master/WORKSPACE#L4
[2] https://gerrit-review.googlesource.com/c/gerrit/+/269382
