### ISSUE TITLE
Please document copyright holders

### ISSUE THREAD

**Issue by olekw** [bazelbuild/java_tools#31]
Please add an AUTHORS file or similar that documents who holds the copyright for this project.

**Comment by olekw** [comment]
Would it be accurate to list @iirina, @davido, and @comius as the copyright holders for this repository?

**Comment by davido** [comment]
@olekw All attributions go to Bazel team.

**Comment by olekw** [comment]
@davido, thanks for the response! Unfortunately, teams can not hold copyright, only legal entities may do so. And only a copyright holder can release a work under an open source license. That is obviously something people take very seriously when they will be distributing said work. :)

If this repository has the same copyright holders as the bazel repository, would it be possible to copy the AUTHORS and CONTRIBUTORS files from that repository into this one? Thanks!
