### ISSUE TITLE
Release:  java_tools_javac11-v10.1 (with Java 15 toolchain support)

### ISSUE THREAD

**Issue by davido** [bazelbuild/java_tools#33]
Now, that https://github.com/bazelbuild/bazel/issues/11871 is landed, there should be new release with JDK 15 toolchain support.

Ideally, Bazel would consume this new `java_tools` per default, so that Bazel users could just select between supported toolchains: 8, 11, 14 and 15.

**Comment by comius** [comment]
There is a failing test for java_tools on linux https://github.com/bazelbuild/bazel/issues/12244

**Comment by comius** [comment]
Creating release artifacts for rc1: https://buildkite.com/bazel-trusted/java-tools-binaries-java/builds/149

**Comment by comius** [comment]
Testing release candidates: https://github.com/bazelbuild/bazel/pull/12302 and https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/1710

**Comment by comius** [comment]
All tests green, except for bazelisk on Windows, which seem unrelated.

Published the release: https://github.com/bazelbuild/java_tools/releases/tag/javac11_v10.1

**Comment by davido** [comment]
Thanks!
