### ISSUE TITLE
Conduct java_tools release with Java 16 toolchain

### ISSUE THREAD

**Issue by davido** [bazelbuild/java_tools#48]
This PR implemented Java 16 toolchain: https://github.com/bazelbuild/bazel/pull/13274.

**Comment by comius** [comment]
java_tools with Jacoco 8.6 were released, for Java 16 toolchain the release is not needed

**Comment by davido** [comment]
Thanks, I confirmed that Java 16 toolchain works as expected on Bazel@HEAD.
