### ISSUE TITLE
Release darwin aarch64 archives

### ISSUE THREAD

**Issue by mauriciogg** [bazelbuild/java_tools#57]
Only x86_64 versions of java_tools exist. M1 macs are becoming the preferred machine for a lot of developers. Ideally there should be architecture specific releases.

**Comment by meteorcloudy** [comment]
@comius This is possible now since Bazel CI has added Apple Silicon machines.

**Comment by hvadehra** [comment]
This is fixed after https://github.com/bazelbuild/bazel/issues/17780 . java_tools for darwin are now separately available for x86_64 and arm64 after v12.0 : https://github.com/bazelbuild/java_tools/releases/tag/java_v12.0

**Comment by hvadehra** [comment]
Since https://github.com/bazelbuild/bazel/commit/c9e3eeb2f34d66e2c8bcccd32786ea75c357497e was already taken in 6.2.0, is this really needed? That change already added support for java_tools for both darwin architechtures (just with a fat universal binary and not separate binaries).

**Comment by meteorcloudy** [comment]
Oh, I see, then we are all good, thanks!
