### ISSUE TITLE
java_tools 12.0

### ISSUE THREAD

**Issue by hvadehra** [bazelbuild/java_tools#66]
Step 4 of https://github.com/bazelbuild/bazel/issues/17780

Decided to bump up the major version from v11 to v12 since this represents a significant (while non-breaking) change.

build: https://buildkite.com/bazel-trusted/java-tools-binaries-java/builds/218

commit_hash: cfef67da634996f09e5f2509e198cc73c88ce8b2
version: 12.0
rc: 1

```
src/create_java_tools_release.sh --commit_hash cfef67da634996f09e5f2509e198cc73c88ce8b2 --java_tools_version 12.0 --rc 1 --release false

release_candidates/java/v12.0/java_tools-v12.0-rc1.zip 6efab6ca6e16e02c90e62bbd08ca65f61527984ab78564ea7ad7a2692b2ffdbb
release_candidates/java/v12.0/java_tools_linux-v12.0-rc1.zip 4b8366b780387fc5ce69527ed287f2b444ee429d3325305ad062c92ac43c7fb6
release_candidates/java/v12.0/java_tools_windows-v12.0-rc1.zip 7b938f0c67d9d390f10489b1b9a4dabb51e39ecc94532c3acdf8c4c16900457f
release_candidates/java/v12.0/java_tools_darwin_x86_64-v12.0-rc1.zip abc434be713ee9e1fd6525d7a7bd9d7cdff6e27ae3ca9d96420490e7ff6e28a3
release_candidates/java/v12.0/java_tools_darwin_arm64-v12.0-rc1.zip 24a47a5557ee2ccdacd10a54fe4c15d627c6aeaf7596a5dccf2e11a866a5a32a
```

Bazel PR: https://github.com/bazelbuild/bazel/pull/17802
Presubmit: https://buildkite.com/bazel/bazel-bazel-github-presubmit/builds/14831
Downstream: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2912

cc: @keertk @kshyanashree

**Comment by hvadehra** [comment]
I'll check downstream results later and proceed with the release it all looks good. 

However, it appears I have lost some rights on this repo, so might need help with drafting the release here and uploading artifacts.

**Comment by hvadehra** [comment]
Downstream looks good, proceeding with the release

```
src/create_java_tools_release.sh --commit_hash cfef67da634996f09e5f2509e198cc73c88ce8b2 --java_tools_version 12.0 --rc 1 --release true

releases/java/v12.0/java_tools_linux-v12.0.zip 4b8366b780387fc5ce69527ed287f2b444ee429d3325305ad062c92ac43c7fb6
releases/java/v12.0/java_tools_windows-v12.0.zip 7b938f0c67d9d390f10489b1b9a4dabb51e39ecc94532c3acdf8c4c16900457f
releases/java/v12.0/java_tools_darwin_x86_64-v12.0.zip abc434be713ee9e1fd6525d7a7bd9d7cdff6e27ae3ca9d96420490e7ff6e28a3
releases/java/v12.0/java_tools_darwin_arm64-v12.0.zip 24a47a5557ee2ccdacd10a54fe4c15d627c6aeaf7596a5dccf2e11a866a5a32a
releases/java/v12.0/java_tools-v12.0.zip 6efab6ca6e16e02c90e62bbd08ca65f61527984ab78564ea7ad7a2692b2ffdbb
```

**Comment by hvadehra** [comment]
PR to update the release playbook docs: https://github.com/bazelbuild/java_tools/pull/67

**Comment by keertk** [comment]
Created: https://github.com/bazelbuild/java_tools/releases/tag/java_v12.0
@hvadehra can you confirm if it looks ok, please?

**Comment by hvadehra** [comment]
nit: Maybe add a note at the top just this time indicating that darwin_arm64 is now supported?

**Comment by keertk** [comment]
Done. Lmk if you want to rephrase.

**Comment by hvadehra** [comment]
:+1:
