### ISSUE TITLE
[bzlmod] How can it be used by MODULE.bazel

### ISSUE THREAD

**Issue by wondfor** [bazelbuild/java_tools#68]
is it supported for bzlmod?

**Comment by hvadehra** [comment]
`java_tools` is now supplied by `rules_java` (https://github.com/bazelbuild/rules_java/releases/tag/6.3.2) which is available in the BCR.

Example of getting the `java_tools` repos: https://github.com/bazelbuild/bazel/blob/master/MODULE.bazel#L198-L206.
